### ISSUE TITLE
Add alias field in meta json

### ISSUE THREAD

**Issue by ShixiangWang** [hiplot/hiplot-plugin-generator#7]
Do it after 5/8

example:

```
  "alias": ["Area-Chart"],
```

**Comment by ShixiangWang** [comment]
@Miachol 目前这个 alias 字段是必需的吗？

**Comment by Miachol** [comment]
不是

--------------原始邮件--------------
发件人："Shixiang Wang ***@***.***&gt;;
发送时间：2021年5月25日(星期二) 晚上9:37
收件人："hiplot/hiplot-plugin-generator" ***@***.***&gt;;
抄送："Jianfeng ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [hiplot/hiplot-plugin-generator] Add alias field in meta json (#7)
-----------------------------------

 

 
@Miachol 目前这个 alias 字段是必需的吗？
